# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

base:
  outputs:

    dev:
      type: duckdb

  target: dev
    outputs:
      dev:
        type: bigquery
        location: EU