version: 2

models:
  - name: fact_crash_weather_enriched
    description: >
      NYC Collisions data for 2013-01-01 through 2024-03-31 enhanced with basic weather data
      Weather data was retrieved for 3 hour intervals. Weather is assigned if the collision timestamp is => then a weather timestamp but less than the next one. 