# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

collisions:
  target: dev
  outputs:
    dev:
      type: bigquery
      location: EU
      method: service-account
      project: nyc-auto-accidents
      dataset: nyc_collisions
      threads: 4
      timeout_seconds: 300
      keyfile: /home/src/google_cloud_key.json

  target: prod
  outputs:
    prod:
      type: bigquery
      location: EU
      method: service-account
      project: nyc-auto-accidents
      dataset: nyc_collisions_prod
      threads: 4
      timeout_seconds: 300
      keyfile: /home/src/google_cloud_key.json
