# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml

collisions:
  target: dev
  outputs:
    dev:
      type: bigquery
      location: EU
      method: service-account
      project: "{{ var('project_id') }}"
      dataset: "{{ var('bq_dataset') }}"
      threads: 4
      timeout_seconds: 300
      keyfile: /home/src/google_cloud_key.json

  target: prod
  outputs:
    prod:
      type: bigquery
      location: EU
      method: service-account
      project: "{{ var('project_id') }}"
      dataset: "{{ var('bq_dataset') }}_prod"
      threads: 4
      timeout_seconds: 300
      keyfile: /home/src/google_cloud_key.json
