version: 2

sources: 
  - name: staging 
    database: nyc-auto-accidents
    schema: nyc_collisions

    tables: 
      - name: crash_external_data
      - name: weather_external_data

models:
  - name: stg_crash_data
    description: >
      Auto collisions reported by the police within NYC
    columns:
        - name: crash_id
          description: Primary key defined by source
          tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
        - name: crash_datetime
          description: crash_datetime
        - name: crash_date
          description: crash_date
        - name: crash_time
          description: crash_time
        - name: crash_month
          description: crash_month
        - name: crash_year
          description: crash_year
        - name: crash_dow
          description: crash_dow
        - name: crash_dow_name
          description: crash_dow_name
        - name: crash_mon_yr
          description: crash_mon_yr
        - name: sun_phase
          description: sun_phase             
        - name: borough
          description: borough
        - name: zip_code
          description: zip_code   
        - name: latitude
          description: latitude
        - name: latitude
          description: latitude
        - name: on_street_name
          description: on_street_name      
        - name: off_street_name
          description: off_street_name
        - name: cross_street_name
          description: cross_street_name   
        - name: number_of_persons_injured
          description: number_of_persons_injured
        - name: number_of_persons_killed
          description: number_of_persons_killed
        - name: number_of_pedestrians_injured
          description: number_of_pedestrians_injured
        - name: number_of_pedestrians_killed
          description: number_of_pedestrians_killed 
        - name: number_of_cyclist_injured
          description: number_of_cyclist_injured
        - name: number_of_cyclist_killed
          description: number_of_cyclist_killed   
        - name: number_of_motorist_injured
          description: number_of_motorist_injured
        - name: number_of_motorist_killed
          description: number_of_motorist_killed
        - name: contributing_factor_vehicle_1
          description: contributing_factor_vehicle_1
        - name: contributing_factor_vehicle_2
          description: contributing_factor_vehicle_2 
        - name: contributing_factor_vehicle_3
          description: contributing_factor_vehicle_3
        - name: contributing_factor_vehicle_4
          description: contributing_factor_vehicle_4   
        - name: contributing_factor_vehicle_5
          description: contributing_factor_vehicle_5
        - name: vehicle_type_code1
          description: vehicle_type_code1
        - name: vehicle_type_code2
          description: vehicle_type_code2
        - name: vehicle_type_code_3
          description: vehicle_type_code_3 
        - name: vehicle_type_code_4
          description: vehicle_type_code_4
        - name: vehicle_type_code_5
          description: vehicle_type_code_5 


  - name: stg_weather_data
    description: >
      3hr weather data for NYC
    columns:
        - name: weather_datetime
          description: Primary key defined by source
          tests:
              - unique:
                  severity: warn
              - not_null:
                  severity: warn
        - name: weather_date
          description: weather_date
        - name: weather_time
          description: weather_time
        - name: temp_c
          description: temp_c
        - name: temp_f
          description: temp_f
        - name: windspeed_miles
          description: windspeed_miles            
        - name: windspeed_kmph
          description: windspeed_kmph
        - name: winddir_degree
          description: winddir_degree   
        - name: winddir16point
          description: winddir16point
        - name: weather_code
          description: weather_code
        - name: weather_desc
          description: weather_desc
        - name: precip_mm
          description: precip_mm